# Site settings
title: MakerLab
email: makerlab@ua.pt
description: >
    The autonomous, interactive, unstructured warehouse management system.
baseurl: ""
url: "https://makerlab.gitlab.io"
owner_name: makerlab
owner_url: https://gitlab.com/makerlab
repository_name: makerlab.gitlab.io
repository_url: https://gitlab.com/makerlab/makerlab.gitlab.io

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
