# Site settings

title: MakerLab
email: makerlab@ua.pt
description: >
    The autonomous, interactive, unstructured warehouse management system.
baseurl: ""
url: "https://makerlab.gitlab.io"
owner_name: makerlab
owner_url: https://gitlab.com/makerlab
repository_name: makerlab.gitlab.io
repository_url: https://gitlab.com/makerlab/makerlab.gitlab.io

show_full_navigation: true

# Build settings

encoding: utf-8
permalink: pretty

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
